### ISSUE TITLE
Init

### ISSUE THREAD

**Issue by 4kimov** [sqids/sqids-ruby#1]
@peterhellberg are you available to [port this one over](https://github.com/sqids/sqids-spec#-porting-to-a-new-language)?

**Comment by peterhellberg** [comment]
@4kimov I'm no longer using Ruby (after spending a decade with Go) so hopefully someone else is up to taking it on 😊

I'm currently on vacation, otherwise I would have reached out earlier about not intending to work on the Ruby port of sqids.

**Comment by 4kimov** [comment]
@peterhellberg Ok, thanks for the heads up. I'll leave this open for now -- if someone is able to port over ~300 LOCs of [TypeScript code](https://github.com/sqids/sqids-spec/blob/main/src/index.ts) to Ruby (+tests), please ping me.
