### ISSUE TITLE
Don't provide a blocklist

### ISSUE THREAD

**Issue by sandstrom** [sqids/sqids-ruby#3]
Instead of being the judge of what words are alright to use, I'd just let the default blocklist be `[]`.

For most scenarios none will care about having a 0.001% chance of a having `Ecock5` as an id. And those that do probably have their own idea of what words are acceptable or not.

We've used auto-generated IDs in our apps for along time and I've yet come across anyone being offended by their password reset token containing some profanity (even though I'm sure it has happened many times!).

**Comment by 4kimov** [comment]
Thanks for the feedback, this has been [discussed in the spec repo before](https://github.com/orgs/sqids/discussions/2#discussioncomment-6282177).

You always have the option of not using any blocklist words by providing an empty blocklist in the constructor.

**Comment by sandstrom** [comment]
Alright, got it!

Yes, setting to an empty list seemed fairly easy, which is the important part.

I'm still somewhat allergic to software, games and other products limiting what type of words are acceptable. That said, these are for IDs, so it's not really an issue if a generated ID gets "censored".

Thanks for a great library! 🏅
